version: '3'

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5431:5431
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid